title: Trevor Bhattacharya # your name (or website title) here
logo: "/images/Profile Picture.jpeg" # your photo (or logo) here
description: Over 5 years of experience leading technical and industrial data based projects. Finding new and useful ways to understand data and build a better world.

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
