title: Trevor Bhattacharya # your name (or website title) here
logo: "/images/Profile Picture.jpeg" # your photo (or logo) here
description: Engineer, data scientist, optimist, and reader of sci-fi <br> Over 5 years of experience leading technical and industrial data based projects.  Finding new and useful ways to understand data and build a better world. <br> <br> <a href="https://www.linkedin.com/in/trevbhatt/"> Connect with me on LinkedIn </a>  <br> <a href="https://www.instagram.com/trevbhatt/"> Follow me on Instagram </a> <br> <a href = "mailto: trevor@trevorb.io"> Send me an email </a>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
